- GRADING.json
- Gemfile
- Gemfile.lock
- app/models/item.rb
- config/database.yml
Small build changes to Gemfile & Gemfile.lock to prepare dependencies for Heroku deployment.  This branch has been successfully pushed and is working on Heroku.  I can merge in any additional work tonight before we make our release tag.
> Build changes for Heroku Deployment

- Gemfile
- features/step_definitions/user_authentication_steps.rb
- features/support/env.rb
- features/users/sign_in.feature
- features/users/sign_up.feature
BDD for signing up. 
This also includes initializing cucumber and making feature/steps files. So we can build add more features and steps files in here! 
> [BDD] Sign up

- Gemfile.lock
- app/controllers/home_controller.rb
- app/controllers/items_controller.rb
- app/helpers/home_helper.rb
- app/models/category.rb
- app/models/item.rb
- app/views/buyers/index.html.erb
- app/views/home/index.html.erb
- app/views/items/_item.html.erb
- app/views/items/index.html.erb
- app/views/items/search.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- db/migrate/20231116032812_add_rating_to_users.rb
- db/migrate/20231116052219_create_categories.rb
- db/migrate/20231116052559_add_category_foreign_key_to_items.rb
- db/migrate/20231116061601_add_featured_columns_to_item.rb
- db/schema.rb
- db/seeds.rb
- spec/helpers/home_helper_spec.rb
- spec/models/category_spec.rb
- spec/requests/home_spec.rb
- spec/views/home/index.html.erb_spec.rb
Adds new homepage with featured items, search bar, and category buttons. Makes the following changes:
- Adds featured and featured_amount_paid to items model
- Adds new Category model that has_many items and updates items to belong_to a category
- Adds simple_search and category_search paths to items_controller
- Adds rating column to users model
- Creates new home controller and home view
This PR changes the category field in the items model from a string to a reference to a category object. This change causes some views to display the category hash instead of the name and might break some routes. I fixed all the ones that I found and I think that some of the views have to be changed anyways. We can decide how to handle this when we  meet.
TBD …
> Create new home page

- Gemfile
- Gemfile.lock
- Guardfile
- app/controllers/buyers_controller.rb
- app/controllers/purchases_controller.rb
- app/models/purchase.rb
- app/models/user.rb
- app/views/buyers/checkout.html.erb
- app/views/buyers/index.html.erb
- app/views/buyers/show.html.erb
- app/views/home/index.html.erb
- app/views/shared/_itemcard.html.erb
- config/routes.rb
- db/migrate/20231123192742_rename_user_id_to_seller_id_in_purchases.rb
- db/migrate/20231123193833_add_buyer_ref_to_purchases.rb
- db/schema.rb
Adds a buyer-facing item show page and checkout page where the buyer can choose to purchase, make an offer, cart, or watchlist the item.  Only purchase functionality is currently implemented but it successfully adds purchases to the database and redirects the user to their purchases page (which needs a touch-up in line with the rest of our design).
> Purchase/Checkout Functionality

- app/views/shared/_navbar.html.erb
Fixes the buttons in the navbar to cover more of their allotted space to ensure that they work as expected.
Fixes # 36
N/A
> [fix] Fixes navbar button functionality

- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/items/edit.html.erb
- app/views/items/new.html.erb
- Sell item and edit item button wasn't working because I was dumb and put it outside the form... Now it should work!
- I also added validation to item's price so that user will not be able to add it if price is not a number
Fixes # ([38](https://github.com/uiowahjmjohnsonselt2023/matts-marketplace/issues/38),  [39](https://github.com/uiowahjmjohnsonselt2023/matts-marketplace/issues/39))
- [] I have added tests that prove my fix is effective or that my feature works
- [] Any dependent changes have been merged and published in downstream modules
> [Fix] Sell item button and Alert fixed

- app/controllers/sellers_controller.rb
- app/views/sellers/index.html.erb
Some style changes to separate out items based on for_sale and sold status.
NA
> Sell item page improvement

- app/controllers/sellers_controller.rb
- app/views/sellers/index.html.erb
Changes styling for sell items page
N/A
> [style] Style changes to sell items

- app/controllers/items_controller.rb
- app/controllers/users_controller.rb
- app/models/review.rb
- app/models/user.rb
- app/views/buyers/show.html.erb
- app/views/shared/_reviews.html.erb
- app/views/users/_user.html.erb
- app/views/users/review.html.erb
- app/views/users/show.html.erb
- config/routes.rb
- db/migrate/20231204002217_create_reviews.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/items_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/factories/reviews.rb
- spec/models/review_spec.rb
Creates the profile page and adds reviews to sellers. Creates two new views: the profile view and the reviews view for creating new reviews. Friday I'll make a style PR to pretty up some of the views.
N/A
> feat: Create profile page

- Gemfile
- features/items/buy_item.feature
- features/items/sell_item.feature
- features/step_definitions/items_steps.rb
- features/step_definitions/user_authentication_steps.rb
- features/support/env.rb
- spec/factories/users.rb
> Test: sell and buy feature testing

- app/javascript/application.js
- app/javascript/items/feature-item.js
Someone changed the application.js file to add some js for the items new page and broke chats. I fixed it. If you are going to change the js at all, please make sure you don't break the chat function.
N/A
> [fix] fixes javascript error that caused chat to break

- app/controllers/items_controller.rb
- app/models/item.rb
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Closes #57
> [fix] category search box nil issue

- app/controllers/purchases_controller.rb
- app/models/purchase.rb
> [fix] more targeted messages when a purchase fails

- features/admin/admin_analytics.feature
- features/admin/admin_manage.feature
- features/step_definitions/admin.steps.rb
- features/support/env.rb
- spec/controllers/admin_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/factories/purchases.rb
- spec/factories/users.rb
- spec/models/purchase_spec.rb
> Admin tests

- Gemfile.lock
- app/controllers/buyers_controller.rb
- app/models/item.rb
- app/views/items/edit.html.erb
- app/views/items/new.html.erb
- app/views/sellers/index.html.erb
- app/views/shared/_itemcard.html.erb
Adds Item editting image upload.  Fixes submitting form before image is uploaded.  (Mostly) properly handles reloads/redirects and preserving form inputs.  Editing images you must click on the border of the image uploader preview.  
> Useability Improvements/Fixes to Image Upload Features

- app/views/chats/_sidebar.html.erb
Removed relic view logic to create a chat before we made them automatically.
> feat: remove temporary chat create

- app/views/buyers/show.html.erb
- app/views/chats/_item_card.html.erb
- app/views/profile/show.html.erb
- app/views/shared/_itemcard.html.erb
- app/views/users/_user.html.erb
- app/views/users/review.html.erb
> Image default logic in views

- app/views/items/edit.html.erb
- app/views/items/new.html.erb
- app/views/profile/edit.html.erb
> Better Image upload submit disabling

- app/controllers/items_controller.rb
- app/models/purchase.rb
- app/views/chats/_chat.html.erb
- app/views/layouts/application.html.erb
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> fix : Miscellaneous fixes and style changes

- app/views/admin/manage_users.html.erb
- app/views/items/admin_edit.html.erb
Fix the view page for admin page.
Now the tables in admin_edit fits in the view port without scrolling horizontally
Haruko
> Admin view fix

- app/views/items/edit.html.erb
- app/views/items/new.html.erb
Everything you could have ever wanted in a HTML text input field.
> Item Featuring handling in new and edit

- app/views/buyers/checkout.html.erb
- app/views/buyers/show.html.erb
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
> fix: price precision

- app/controllers/profile_controller.rb
- spec/controllers/home_controller_spec.rb
- spec/controllers/profile_controller_spec.rb
- spec/controllers/purchases_controller_spec.rb
- spec/factories/items.rb
- spec/factories/users.rb
> [test] Controller tests

- app/controllers/items_controller.rb
- app/controllers/sellers_controller.rb
- app/views/buyers/show.html.erb
- app/views/purchases/show.html.erb
Misc bugs fix.
- Add featured amount paid to root_admin's balance
- Fix a bug where sold items are displayed under for sale items
- Fix a bug where item description in purchase history tab hyperlink redirect to a wrong route.
- Fix a bug where add to wishlist button is displayed even when item is not for sale.
> Misc bug fix

- app/controllers/items_controller.rb
- app/models/item.rb
- app/views/shared/_itemcard.html.erb
- config/routes.rb
> feat: we did it boys

- app/models/item.rb
Fixes issue with category search
> fix: fixes category search

- app/views/profile/show.html.erb
- app/views/purchases/show.html.erb
- app/views/shared/_purchasecard.html.erb
Fix BUGS
- images not showing up in the purchase history
- fix a bug in code for profile show
> Mingi bug fix

- app/controllers/users_controller.rb
Adds review to the list of actions that require user auth
> fix: adds user authentication to reviews

- app/controllers/chats_controller.rb
- app/controllers/users_controller.rb
Adds user auth all chat actions 
TBD
> fix: added user auth to chats
